# -*- coding: utf-8 -*-
"""student_performance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jdKaVuG65EKkAZIbMZOiMUpSyqwszHE4
"""


import streamlit as st
import pandas as pd
import numpy as np
import pickle

def load_model():
  with open('model/stu.pkl','rb')as f:
    model=pickle.load(f)
  return model

model=load_model()
st.title("THE STUDENT PERFORMANCE ANALYSIS")
st.header("Enter The Details")

feature1=st.number_input("Hours Studied",value=0.0)
feature2=st.number_input("Previous Scores",value=0.0)
feature3=st.number_input("Extracurricular Activities",value=0.0)
feature4=st.number_input("Sleep Hours",value=0.0)
feature5=st.number_input("Sample Question Papers Practiced",value=0.0)

input_data=np.array([feature1,feature2,feature3,feature4,feature5])

if st.button("Predict"):
  prediction=model.predict(input_data)
  st.success(f"The Student Performance is {prediction}")

